# Generated by Django 4.0.3 on 2022-03-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_channel_pic_group_pic_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
