# Generated by Django 4.0.3 on 2022-03-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_channel_members_channel_token_group_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='members',
        ),
        migrations.AddField(
            model_name='channel',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
