# Generated by Django 4.0.3 on 2022-03-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_remove_channel_members_channel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
