# Generated by Django 4.0.3 on 2022-03-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_remove_message_file_channel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
