# Generated by Django 4.0.3 on 2022-03-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='seened',
            field=models.BooleanField(default=False),
        ),
    ]
